Rest
studio2faces/cosmoport pull request #1
Opened 2020-08-31 13:17 UTC by studio2faces

All tests are OK

2020-08-31 21:52 UTC, sergeevik requested changes

2020-08-31 21:52 UTC, sergeevik commented on src/main/java/com/space/controller/ShipController.java
> +            if (ship.getProdDate().getTime() < 26194914000000L || ship.getProdDate().getTime() > 33126786000000L)
это магические числа (26194914000000L), читающему и тебе в будущем будет непонятно что это за число и можно ли его менять

2020-08-31 21:52 UTC, sergeevik commented on src/main/java/com/space/controller/ShipController.java
> +            if (ship.getUsed() == null) ship.setUsed(false);
по гугл код стайлу лучше писать действие с новой строки и в скобках

2020-08-31 21:52 UTC, sergeevik commented on src/main/java/com/space/controller/ShipController.java
> +        } catch (NullPointerException e) {
ошибки лучше логировать, а то не поймешь что и где произошло.
Если можешь, то лучше оборачивать конкретную операцию + её атрибуты, чтобы потом не гадать что пошло не так

2020-08-31 21:52 UTC, sergeevik commented on src/main/java/com/space/controller/ShipController.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST);
тоже самое про логирование

2020-08-31 21:52 UTC, sergeevik commented on src/main/java/com/space/model/entity/Ship.java
> +    private Boolean isUsed; //default false (if doesn't exists)
Boolean тут по дефолту будет null
либо убрать коммент, либо сменить на примитив, либо дать дефолтное значение

2020-08-31 21:52 UTC, sergeevik commented on src/main/java/com/space/repository/ShipRepository.java
> +import java.awt.print.Pageable;
лишнее

2020-08-31 21:52 UTC, sergeevik commented on src/main/java/com/space/service/ShipService.java
> +    // Filters
неинформативный комментарий, есть подозрение, что тут когда-то что-то было, но потом удалили, а коммент остался как напоминание

2020-09-01 15:57 UTC, studio2faces commented on src/main/java/com/space/controller/ShipController.java
> +            if (ship.getProdDate().getTime() < 26194914000000L || ship.getProdDate().getTime() > 33126786000000L)
done

2020-09-01 16:05 UTC, studio2faces commented on src/main/java/com/space/controller/ShipController.java
> +            if (ship.getUsed() == null) ship.setUsed(false);
done

2020-09-01 16:07 UTC, studio2faces commented on src/main/java/com/space/model/entity/Ship.java
> +    private Boolean isUsed; //default false (if doesn't exists)
По заданию должен быть Boolean. Коммент был для меня, убрала

2020-09-01 16:07 UTC, studio2faces commented on src/main/java/com/space/repository/ShipRepository.java
> +import java.awt.print.Pageable;
done

2020-09-01 16:08 UTC, studio2faces commented on src/main/java/com/space/service/ShipService.java
> +    // Filters
По задумке это был коммент, отделяющий методы фильтров от остальных. Но раз это не понятно, то убираю :)

2020-09-03 20:34 UTC, sergeevik requested changes

2020-09-03 20:34 UTC, sergeevik commented on src/main/java/com/space/model/entity/Ship.java
> +    public static void main(String[] args) {
лишнее

2020-09-07 08:34 UTC, studio2faces commented on src/main/java/com/space/model/entity/Ship.java
> +    public static void main(String[] args) {
done

2020-09-07 08:34 UTC, merged